# Generated by Django 4.2.3 on 2023-08-31 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_certifyinginstitution_certificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="time_stamp",
            new_name="timestamp",
        ),
    ]
