# Generated by Django 4.2.3 on 2023-08-31 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_rename_time_stamp_certificate_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certifying_institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="projects.certifyinginstitution",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(
                related_name="certificates", to="projects.profile"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
